version: "3.9"
services:
  web:
    image: nginx:alpine
    volumes:
        - ./src:/src
        - ./infra/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 8080:8080
    working_dir: /src
    links:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: app
      MYSQL_PASSWARD: app_passwd
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./infra/mysql/test.sql:/docker-entrypoint-initdb.d/test.sql

  php:
    build: ./infra/php/
    volumes:
        - ./src:/src
    working_dir: /src
    links:
      - mysql

volumes:
  mysql-datas:
  php-fpm: